routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::prefix('/')->group(function(){

    Route::get('/','PanelController@index')->name('panel');

    Route::resource('profitsandloss','ProfitsAndLossController');

    Route::resource('accountstatements','AccountStatementsController');
});

app/Http/Controllers/AccountStatementsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\AccountStatement;
use App\Model\AccoutStatementType;
use App\Model\User;
use Validator;

class AccountStatementsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $accountStatements = AccountStatement::orderBy('created_at','DESC')->paginate(20);

        return View('accountstatements.index')->with('statements',$accountStatements);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        $accountStatementTypes = AccoutStatementType::all();
        return View('accountstatements.create')
                ->with('users',$users)
                ->with('statementTypes',$accountStatementTypes);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'description' => 'required',
            'average_odds' => 'required',
            'stopped' => 'required',
            'state' => 'required',
            'rd' => 'required',
            'rc' => 'required',
            'balance' => 'required',
            'ref_id' => 'required'
        ]);

        if($validator->fails()){
            return redirect()->back()->with('errors',$validator->errors()->all());
        }
        else{
            $accountStatement = new AccountStatement;

            $accountStatement->ref_id = $request->input('ref_id');
            $accountStatement->placed = $request->input('placed');
            $accountStatement->description = $request->input('description');
            $accountStatement->average_odds = $request->input('average_odds');
            $accountStatement->stopped = $request->input('stopped');
            $accountStatement->state = $request->input('state');
            $accountStatement->rd = $request->input('rd');
            $accountStatement->rc = $request->input('rc');
            $accountStatement->balance = $request->input('balance');
            $accountStatement->user_id = $request->input('user_id');
            $accountStatement->account_statement_types_id = $request->input('account_statement_types_id');

            $accountStatement->save();

            return redirect()->route('accountstatements.index');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PanelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PanelController extends Controller
{
    public function index(){
        return View('panel.index');
    }
}

app/Http/Controllers/ProfitsAndLossController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\ProfitsAndLoss;

class ProfitsAndLossController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $profits = ProfitsAndLoss::paginate(20);
        return View('profitsandloss.index')->with('profits',$profits);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('profitsandloss.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $profit = new ProfitsAndLoss;
        $profit->market = $request->input('market');
        $profit->start_time = $request->input('start_time');
        $profit->resolution_date = $request->input('resolution_date');
        $profit->profit_prejudice = $request->input('profit_prejudice');

        $profit->save();

        return redirect()->route('profitsandloss.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/accountstatements/create.blade.php
@extends('layout.panel')

@section('content')
<div class="content">
  <div class="row">
    <div class="col-lg-12">
      @if(Session::has('errors'))
        <div class="alert alert-danger"><?= implode("<br>", Session::get('errors'))?></div>
      @endif
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Add Account Statement</h3>
        </div>
        <form action="{{route('accountstatements.store')}}" method="post">
          {{ csrf_field() }}
          <div class="box-body">

            <div class="col-lg-4">
              <div class="form-group">
                <select class="form-control" name="user_id">
                  @foreach($users as $user)
                    <option value="{{$user->id}}">{{$user->name}}</option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="col-lg-4">
              <div class="form-group">
                <select class="form-control" name="account_statement_types_id">
                  @foreach($statementTypes as $type)
                    <option value="{{$type->id}}">{{$type->description}}</option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="col-lg-3">
              <div class="form-group">
                <input type="text" class="form-control" name="ref_id" placeholder="Ref Id">
              </div>
            </div>

            <div class="col-lg-3">
              <div class="form-group">
                <input type="datetime" class="form-control" name="placed" placeholder="Colocada">
              </div>
            </div>
            
            <div class="col-lg-6">
              <div class="form-group">
                <input type="text" class="form-control" name="description" placeholder="Descrição">
              </div>
            </div>

            <div class="col-lg-3">
              <div class="form-group">
                <input type="text" class="form-control" name="average_odds" placeholder="Média probabilidades">
              </div>
            </div>

            <div class="col-lg-2">
              <div class="form-group">
                <input type="text" class="form-control" name="stopped" placeholder="Parada">
              </div>
            </div>

            <div class="col-lg-3">
              <div class="form-group">
                <input type="text" class="form-control" name="state" placeholder="Estado">
              </div>
            </div>

            <div class="col-lg-2">
              <div class="form-group">
                <input type="text" class="form-control" name="rd" placeholder="RD">
              </div>
            </div>

            <div class="col-lg-2">
              <div class="form-group">
                <input type="text" class="form-control" name="rc" placeholder="RC">
              </div>
            </div>

            <div class="col-lg-3">
              <div class="form-group">
                <input type="text" class="form-control" name="balance" placeholder="Saldo">
              </div>
            </div>

          </div>
          <div class="box-footer">
            <input type="submit" class="btn btn-success" value="Salvar">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="/template/plugins/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="/template/plugins/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />

<script type="text/javascript">
    $(function () {
        $('input[type=datetime]').datetimepicker({
          format: 'YYYY-MM-DD H:mm'
        });
    });
</script>
@endsection

resources/views/accountstatements/index.blade.php
@extends('layout.panel')

@section('content')
<div class="content-header"></div>
<div class="content">
  <div class="row">
    <div class="col-lg-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Statements</h3>
          <div class="box-tools pull-right">
            <a href="{{route('accountstatements.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i></a>
          </div>
        </div>
        <div class="box-body no-padding">
          <table class="table table-responsive">
            <tbody>
              <tr>
                <th>Fixada</th>
                <th>Ref Id</th>
                <th>Colocada</th>
                <th>Descrição</th>
                <th>Média probabilidades</th>
                <th>Parada</th>
                <th>Estado</th>
                <th>RD<br>(€)</th>
                <th>RC<br>(€)</th>
                <th>Saldo<br>(€)</th>

              </tr>
              @foreach($statements as $statement)
                <tr>
                  <td>{{$statement->createdFormated()}}</td>
                  <td>{{$statement->ref_id}}</td>
                  <td>{{$statement->placedFormated()}}</td>
                  <td>{{$statement->description}}</td>
                  <td>{{number_format($statement->average_odds,2,',','.')}}</td>
                  <td>{{number_format($statement->stoped,2,',','.')}}</td>
                  <td>{{$statement->state}}</td>
                  <td>{{number_format($statement->rd,2,',','.')}}</td>
                  <td>{{number_format($statement->rc,2,',','.')}}</td>
                  <td>{{number_format($statement->balance,2,',','.')}}</td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        <div class="box-footer">
          {{$statements->links()}}
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/layout/elements/aside.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li>
          <a href="{{route('panel')}}">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
        </li>
        <li>
          <a href="{{route('profitsandloss.index')}}">
            <i class="fa fa-table"></i> <span>Profits and Loss</span>
          </a>
        </li>
        <li>
          <a href="{{route('accountstatements.index')}}">
            <i class="fa fa-table"></i> <span>Account Statements</span>
          </a>
        </li>
        
<!--         
        <li class="treeview">
          <a href="#">
            <i class="fa fa-laptop"></i>
            <span>UI Elements</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
            <li><a href="pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
            <li><a href="pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
            <li><a href="pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
            <li><a href="pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
            <li><a href="pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-edit"></i> <span>Forms</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
            <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
            <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-table"></i> <span>Tables</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
            <li><a href="pages/tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
          </ul>
        </li>
        <li>
          <a href="pages/calendar.html">
            <i class="fa fa-calendar"></i> <span>Calendar</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-red">3</small>
              <small class="label pull-right bg-blue">17</small>
            </span>
          </a>
        </li>
        <li>
          <a href="pages/mailbox/mailbox.html">
            <i class="fa fa-envelope"></i> <span>Mailbox</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-yellow">12</small>
              <small class="label pull-right bg-green">16</small>
              <small class="label pull-right bg-red">5</small>
            </span>
          </a>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-folder"></i> <span>Examples</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
            <li><a href="pages/examples/profile.html"><i class="fa fa-circle-o"></i> Profile</a></li>
            <li><a href="pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
            <li><a href="pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
            <li><a href="pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
            <li><a href="pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
            <li><a href="pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
            <li><a href="pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
            <li><a href="pages/examples/pace.html"><i class="fa fa-circle-o"></i> Pace Page</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-share"></i> <span>Multilevel</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
            <li class="treeview">
              <a href="#"><i class="fa fa-circle-o"></i> Level One
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                <li class="treeview">
                  <a href="#"><i class="fa fa-circle-o"></i> Level Two
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                  </a>
                  <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
          </ul>
        </li>
        <li><a href="https://adminlte.io/docs"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
        <li class="header">LABELS</li>
        <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li> -->
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

resources/views/layout/panel.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Betfair | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/template/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/template/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/template/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/template/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="/template/dist/css/skins/_all-skins.min.css">
  <!-- Morris chart -->
  <link rel="stylesheet" href="/template/bower_components/morris.js/morris.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="/template/bower_components/jvectormap/jquery-jvectormap.css">
  <!-- Date Picker -->
  <link rel="stylesheet" href="/template/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="/template/bower_components/bootstrap-daterangepicker/daterangepicker.css">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="/template/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

  <!-- jQuery 3 -->
  <script src="/template/bower_components/jquery/dist/jquery.min.js"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="/template/bower_components/jquery-ui/jquery-ui.min.js"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button);
  </script>
  <!-- Bootstrap 3.3.7 -->
  <script src="/template/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <!-- Morris.js charts -->
  <script src="/template/bower_components/raphael/raphael.min.js"></script>
  <script src="/template/bower_components/morris.js/morris.min.js"></script>
  <!-- Sparkline -->
  <script src="/template/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
  <!-- jvectormap -->
  <script src="/template/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
  <script src="/template/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
  <!-- jQuery Knob Chart -->
  <script src="/template/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
  <!-- daterangepicker -->
  <script src="/template/bower_components/moment/min/moment.min.js"></script>
  <script src="/template/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
  <!-- datepicker -->
  <script src="/template/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
  <!-- Bootstrap WYSIHTML5 -->
  <script src="/template/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
  <!-- Slimscroll -->
  <script src="/template/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
  <!-- FastClick -->
  <script src="/template/bower_components/fastclick/lib/fastclick.js"></script>
  <!-- AdminLTE App -->
  <script src="/template/dist/js/adminlte.min.js"></script>
</head>
<body class="hold-transition skin-yellow-light sidebar-mini">
  <div class="wrapper">
    @include('layout.elements.header')
    @include('layout.elements.aside')

    <div class="content-wrapper">
      @yield('content')
    </div>

  </div>
</body>
</html>

resources/views/panel/index.blade.php
@extends('layout.panel')

@section('content')
  <div class="content-header">
    <h1>Dashboard</h1>
  </div>
@endsection

resources/views/profitsandloss/create.blade.php
@extends('layout.panel')

@section('content')
<div class="content-header"></div>
<div class="content">
  <div class="row">
    <div class="col-lg-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title"> Add Profits And Loss</h3>
        </div>
        <form role="form" action="{{route('profitsandloss.store')}}" method="post">
          {{ csrf_field() }}
          <div class="box-body">
            <div class="col-lg-4">
              <div class="form-group">
                <input type="text" class="form-control" name="market" placeholder="Market">
              </div>
            </div>
            <div class="col-lg-3">
              <div class="form-group">
                <input type="datetime" class="form-control" name="start_time" placeholder="Start time">
              </div>
            </div>
            <div class="col-lg-3">
              <div class="form-group">
                <input type="datetime" class="form-control" name="resolution_date" placeholder="Resolution time">
              </div>
            </div>
            <div class="col-lg-2">
              <div class="form-group">
                <input type="text" class="form-control" name="profit_prejudice" placeholder="Prejudice">
              </div>
            </div>
            
            
            <div class="form-group"></div>
            <div class="form-group"></div>
          </div>
          <div class="box-footer">
            <input type="submit" value="Salvar" class="btn btn-success">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="/template/plugins/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="/template/plugins/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />

<script type="text/javascript">
    $(function () {
        $('input[type=datetime]').datetimepicker({
          format: 'YYYY-MM-DD H:mm'
        });
    });
</script>

@endsection

resources/views/profitsandloss/index.blade.php
@extends('layout.panel')

@section('content')
<div class="content-header"></div>
<div class="content">
  <div class="row">
    <div class="col-lg-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Profits And Loss</h3>
          <div class="box-tools pull-right">
            <a href="{{route('profitsandloss.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i></a>
          </div>
        </div>
        <div class="box-body no-padding">
          <table class="table table-responsive">
            <tbody>
              <tr align="center">
                <th align="left">Mercado</th>
                <th>Hora de inicio</th>
                <th>Data da última resolução</th>
                <th>Lucro/prejuízo (€)</th>
              </tr>
              @foreach($profits as $profit)
                <tr>
                  <td> {{$profit->market}}</td>
                  <td>{{$profit->start_timeFormated()}}</td>
                  <td>{{$profit->resolution_dateFormated()}}</td>
                  <td>{{$profit->profit_prejudice}}</td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        <div class="box-footer">
          {{$profits->links()}}
        </div>
      </div>
    </div>
  </div>
</div>
@endsection